ALTER TABLE vendor_verification_step
    ADD COLUMN IF NOT EXISTS aadhaar_file_url VARCHAR(500) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS aadhaar_file_name VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS aadhaar_file_mime VARCHAR(120) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS aadhaar_file_size BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS pan_file_url VARCHAR(500) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS pan_file_name VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS pan_file_mime VARCHAR(120) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS pan_file_size BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMPTZ NULL;
